# Generated by Django 2.2 on 2019-04-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("boltstream", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="type",
            field=models.CharField(
                choices=[
                    ("other", "Other"),
                    ("playbyplay", "Play by play"),
                    ("subtitles", "Subtitles"),
                ],
                default="other",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="stream",
            name="feeds",
            field=models.ManyToManyField(
                blank=True, related_name="streams", to="boltstream.Feed"
            ),
        ),
    ]
