# Generated by Django 2.2 on 2019-05-01 13:16

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("boltstream", "0002_auto_20190429_2043")]

    operations = [
        migrations.CreateModel(
            name="StreamSession",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Started"
                    ),
                ),
                (
                    "stopped_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Stopped"),
                ),
                (
                    "ingest_host",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="boltstream.Stream",
                    ),
                ),
            ],
            options={"ordering": ("started_at", "stopped_at")},
        )
    ]
